version: '3.8'
name: logistics-management-system
services:
  server:
    build: .
    environment:
      HTTP_PORT: 3000
      DB_URL: postgresql://postgres:postgres@db:5432/logistics?sslmode=disable
    ports:
      - "4000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_DB: logistics
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "4001:5432"
    healthcheck:
      test: pg_isready
      interval: 1s
      timeout: 10s
      retries: 10
